# -*- coding: utf-8 -*-
"""3d-medical-image-segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mb3YYc6QTCiNzQnLqzxQB3ft8967JZTp
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        (os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import nibabel as nib
import os
from pathlib import Path
from sklearn.model_selection import train_test_split
import math
from tqdm import tqdm

# ==================== MODEL ARCHITECTURE ====================

config = {
    "patch": 16,
    "dim": 768,
    "n_heads": 12,
    "layers": 12,
    "image_size": 128,
    "image_layer": 128,
    "channel": 4
}

class Deconv(nn.Module):
    def __init__(self, in_dim, out_dim):
        super().__init__()
        self.deconv = nn.ConvTranspose3d(in_dim, out_dim, kernel_size=2, stride=2, padding=0, output_padding=0)

    def forward(self, x):
        return self.deconv(x)

class Conv(nn.Module):
    def __init__(self, in_dim, out_dim, k):
        super().__init__()
        self.conv = nn.Conv3d(in_dim, out_dim, kernel_size=k, stride=1, padding=((k - 1) // 2))

    def forward(self, x):
        return self.conv(x)

class ConvBlock(nn.Module):
    def __init__(self, indim, outdim):
        super().__init__()
        self.conv = Conv(indim, outdim, 3)
        self.norm = nn.BatchNorm3d(outdim)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.conv(x)
        x = self.norm(x)
        x = self.activation(x)
        return x

class DeconvBlock(nn.Module):
    def __init__(self, indim, outdim):
        super().__init__()
        self.deconv = Deconv(indim, outdim)
        self.conv = Conv(outdim, outdim, 3)
        self.norm = nn.BatchNorm3d(outdim)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.deconv(x)
        x = self.conv(x)
        x = self.norm(x)
        x = self.activation(x)
        return x

class GELU(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 0.5 * x * (1.0 + torch.tanh(math.sqrt(2.0 / math.pi) * (x + 0.044715 * torch.pow(x, 3.0))))

class PatchEmbeddings(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.patch_size = cfg["patch"]
        self.img_size = cfg["image_size"]
        self.hidden_size = cfg["dim"]
        self.depth = cfg["image_layer"]
        self.no_patch = (
            (self.img_size // self.patch_size) *
            (self.img_size // self.patch_size) *
            (self.depth // self.patch_size)
        )
        self.layer = nn.Conv3d(cfg["channel"], self.hidden_size, kernel_size=self.patch_size, stride=self.patch_size)

    def forward(self, x):
        x = self.layer(x)
        x = x.flatten(2).transpose(1, 2)
        return x

class Embeddings(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.patch_embed = PatchEmbeddings(config)
        self.pos_embed = nn.Parameter(torch.randn(1, self.patch_embed.no_patch, config["dim"]))

    def forward(self, x):
        x = self.patch_embed(x)
        batch_size, _, _ = x.shape
        x = self.pos_embed + x
        return x

class SelfAttention(nn.Module):
    def __init__(self, inp_dim, outdim, cfg):
        super().__init__()
        self.w_q = nn.Linear(inp_dim, outdim)
        self.w_k = nn.Linear(inp_dim, outdim)
        self.w_v = nn.Linear(inp_dim, outdim)
        self.dropout = nn.Dropout(0.1)

    def forward(self, x):
        q = self.w_q(x)
        k = self.w_k(x)
        v = self.w_v(x)
        attn = q @ k.transpose(1, 2)
        dim_k = k.shape[-1]
        attn = attn / dim_k ** 0.5
        attn_scores = torch.softmax(attn, dim=-1)
        attn_scores = self.dropout(attn_scores)
        return attn_scores @ v

class MultiHeadAttention(nn.Module):
    def __init__(self, n_heads, inp_dim, cfg):
        super().__init__()
        self.head_dim = inp_dim // n_heads
        self.n_heads = n_heads
        self.heads = nn.ModuleList([SelfAttention(inp_dim, self.head_dim, cfg) for _ in range(n_heads)])

    def forward(self, x):
        outputs = [head(x) for head in self.heads]
        x = torch.cat(outputs, dim=-1)
        return x

class MLP(nn.Module):
    def __init__(self, inp_dim, drop_rate):
        super().__init__()
        self.layer1 = nn.Linear(inp_dim, 4 * inp_dim)
        self.layer2 = nn.Linear(4 * inp_dim, inp_dim)
        self.dropout = nn.Dropout(drop_rate)
        self.activation = GELU()

    def forward(self, x):
        x = self.layer1(x)
        x = self.activation(x)
        x = self.layer2(x)
        x = self.dropout(x)
        return x

class Transformer(nn.Module):
    def __init__(self, dim, n_heads, cfg):
        super().__init__()
        self.norm1 = nn.LayerNorm(dim)
        self.norm2 = nn.LayerNorm(dim)
        self.attn = MultiHeadAttention(n_heads, dim, cfg)
        self.mlp = MLP(dim, 0.1)

    def forward(self, x):
        residue = x
        x = self.norm1(x)
        x = self.attn(x)
        x = residue + x
        residue = x
        x = self.norm2(x)
        x = self.mlp(x)
        x = residue + x
        return x

class Encoder(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.layers = nn.ModuleList([
            Transformer(cfg["dim"], cfg["n_heads"], cfg) for _ in range(cfg["layers"])
        ])
        self.embedding = Embeddings(cfg)

    def forward(self, x, intermidiate=True):
        x = self.embedding(x)
        if not intermidiate:
            for layer in self.layers:
                x = layer(x)
            return x
        outputs = {}
        for i, layer in enumerate(self.layers):
            x = layer(x)
            if (i + 1) % 3 == 0:
                outputs[f'z{i+1}'] = x
        return outputs

class Unetr(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.series1 = nn.Sequential(
            ConvBlock(4, 32),
            ConvBlock(32, 64)
        )
        self.series2 = nn.Sequential(
            DeconvBlock(cfg["dim"], 512),
            DeconvBlock(512, 256),
            DeconvBlock(256, 128)
        )
        self.series3 = nn.Sequential(
            DeconvBlock(cfg["dim"], 512),
            DeconvBlock(512, 256),
        )
        self.series4 = nn.Sequential(
            DeconvBlock(cfg["dim"], 512),
        )
        self.series5 = Deconv(cfg["dim"], 512)
        self.series6 = nn.Sequential(
            ConvBlock(1024, 512),
            ConvBlock(512, 512)
        )
        self.series7 = Deconv(512, 256)
        self.series8 = nn.Sequential(
            ConvBlock(512, 256),
            ConvBlock(256, 256)
        )
        self.series9 = nn.Sequential(
            DeconvBlock(256, 128),
        )
        self.series10 = nn.Sequential(
            ConvBlock(256, 128),
            ConvBlock(128, 128),
        )
        self.series11 = Deconv(128, 64)
        self.series12 = nn.Sequential(
            ConvBlock(128, 64),
            ConvBlock(64, 16),
            nn.Conv3d(16, 4, kernel_size=1, padding=0)
        )
        self.encoder = Encoder(config)
        self.cfg = cfg

    def forward(self, x):
        residue = self.series1(x)
        outs = self.encoder(x)
        z3 = outs["z3"].transpose(1, 2).view(-1, 768, self.cfg["image_layer"]//16, self.cfg["image_size"]//16, self.cfg["image_size"]//16)
        z6 = outs["z6"].transpose(1, 2).view(-1, 768, self.cfg["image_layer"]//16, self.cfg["image_size"]//16, self.cfg["image_size"]//16)
        z9 = outs["z9"].transpose(1, 2).view(-1, 768, self.cfg["image_layer"]//16, self.cfg["image_size"]//16, self.cfg["image_size"]//16)
        z12 = outs["z12"].transpose(1, 2).view(-1, 768, self.cfg["image_layer"]//16, self.cfg["image_size"]//16, self.cfg["image_size"]//16)

        z12 = self.series5(z12)
        z9 = self.series4(z9)
        z19 = torch.cat([z9, z12], dim=1)
        t6 = self.series6(z19)
        t7 = self.series7(t6)
        z6 = self.series3(z6)
        t8 = torch.cat([z6, t7], dim=1)
        t9 = self.series8(t8)
        t9 = self.series9(t9)
        z3 = self.series2(z3)
        t10 = torch.cat([z3, t9], dim=1)
        t11 = self.series10(t10)
        t11 = self.series11(t11)
        t12 = torch.cat([residue, t11], dim=1)
        t13 = self.series12(t12)
        return t13

# ==================== DATASET ====================

class BraTSDataset(Dataset):
    def __init__(self, data_dir, patient_ids, target_size=(128, 128, 128)):
        """
        BraTS 2020 Dataset
        Args:
            data_dir: Path to BraTS2020_TrainingData folder
            patient_ids: List of patient folder names
            target_size: Target volume size (H, W, D)
        """
        self.data_dir = Path(data_dir)
        self.patient_ids = patient_ids
        self.target_size = target_size

    def __len__(self):
        return len(self.patient_ids)

    def normalize(self, volume):
        """Normalize volume to [0, 1]"""
        volume = volume.astype(np.float32)
        if volume.max() > 0:
            volume = (volume - volume.min()) / (volume.max() - volume.min())
        return volume

    def resize_volume(self, volume, target_shape):
        """Simple resize by center cropping or padding"""
        current_shape = volume.shape

        # Calculate start indices for cropping/padding
        starts = [(cs - ts) // 2 if cs > ts else 0 for cs, ts in zip(current_shape, target_shape)]
        ends = [s + ts for s, ts in zip(starts, target_shape)]

        # Create output volume
        output = np.zeros(target_shape, dtype=volume.dtype)

        # Calculate valid ranges
        for i in range(3):
            if current_shape[i] < target_shape[i]:
                starts[i] = (target_shape[i] - current_shape[i]) // 2
                ends[i] = starts[i] + current_shape[i]

        # Copy data
        if all(cs >= ts for cs, ts in zip(current_shape, target_shape)):
            # Crop
            output = volume[starts[0]:ends[0], starts[1]:ends[1], starts[2]:ends[2]]
        else:
            # Pad
            src_slices = [slice(max(0, -s), min(cs, cs - s + ts)) for s, cs, ts in zip(starts, current_shape, target_shape)]
            dst_slices = [slice(max(0, s), max(0, s) + (src_s.stop - src_s.start)) for s, src_s in zip(starts, src_slices)]
            output[dst_slices[0], dst_slices[1], dst_slices[2]] = volume[src_slices[0], src_slices[1], src_slices[2]]

        return output

    def __getitem__(self, idx):
        patient_id = self.patient_ids[idx]
        patient_path = self.data_dir / patient_id

        # Check what files exist - try both .nii.gz and .nii
        files = list(patient_path.glob("*.nii.gz")) + list(patient_path.glob("*.nii"))
        if not files:
            raise FileNotFoundError(f"No .nii or .nii.gz files found in {patient_path}")

        # Try to find files with different naming patterns
        flair_file = None
        t1_file = None
        t1ce_file = None
        t2_file = None
        seg_file = None

        for f in files:
            fname = f.name.lower()
            if 'flair' in fname:
                flair_file = f
            elif 't1ce' in fname or 't1_ce' in fname:
                t1ce_file = f
            elif 't1' in fname and 'ce' not in fname:
                t1_file = f
            elif 't2' in fname:
                t2_file = f
            elif 'seg' in fname:
                seg_file = f

        # Verify all files are found
        if not all([flair_file, t1_file, t1ce_file, t2_file, seg_file]):
            raise FileNotFoundError(f"Missing modality files in {patient_path}. Found: {[f.name for f in files]}")

        # Load all modalities
        flair = nib.load(str(flair_file)).get_fdata()
        t1 = nib.load(str(t1_file)).get_fdata()
        t1ce = nib.load(str(t1ce_file)).get_fdata()
        t2 = nib.load(str(t2_file)).get_fdata()

        # Load segmentation mask
        seg = nib.load(str(seg_file)).get_fdata()

        # Resize volumes
        flair = self.resize_volume(flair, self.target_size)
        t1 = self.resize_volume(t1, self.target_size)
        t1ce = self.resize_volume(t1ce, self.target_size)
        t2 = self.resize_volume(t2, self.target_size)
        seg = self.resize_volume(seg, self.target_size)

        # Normalize
        flair = self.normalize(flair)
        t1 = self.normalize(t1)
        t1ce = self.normalize(t1ce)
        t2 = self.normalize(t2)

        # Stack modalities: (4, H, W, D)
        image = np.stack([flair, t1, t1ce, t2], axis=0)

        # Convert seg to multi-class (4 classes: 0=background, 1=NCR/NET, 2=ED, 4=ET)
        # We'll convert to 4 channels for each class
        mask = np.zeros((4, *self.target_size), dtype=np.float32)
        mask[0] = (seg == 0).astype(np.float32)  # Background
        mask[1] = (seg == 1).astype(np.float32)  # NCR/NET
        mask[2] = (seg == 2).astype(np.float32)  # ED
        mask[3] = (seg == 4).astype(np.float32)  # ET

        return torch.FloatTensor(image), torch.FloatTensor(mask)

# ==================== LOSS FUNCTION ====================

class DiceLoss(nn.Module):
    def __init__(self, smooth=1.0):
        super().__init__()
        self.smooth = smooth

    def forward(self, pred, target):
        pred = torch.sigmoid(pred)
        intersection = (pred * target).sum(dim=(2, 3, 4))
        union = pred.sum(dim=(2, 3, 4)) + target.sum(dim=(2, 3, 4))
        dice = (2. * intersection + self.smooth) / (union + self.smooth)
        return 1 - dice.mean()

class BCEDiceLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.bce = nn.BCEWithLogitsLoss()
        self.dice = DiceLoss()

    def forward(self, pred, target):
        return self.bce(pred, target) + self.dice(pred, target)

# ==================== METRICS ====================

def dice_score(pred, target, threshold=0.5):
    """Calculate Dice score"""
    pred = torch.sigmoid(pred) > threshold
    pred = pred.float()

    intersection = (pred * target).sum(dim=(2, 3, 4))
    union = pred.sum(dim=(2, 3, 4)) + target.sum(dim=(2, 3, 4))
    dice = (2. * intersection + 1e-7) / (union + 1e-7)
    return dice.mean().item()

# ==================== DATASET VERIFICATION ====================

def verify_dataset(data_dir, num_samples=3):
    """
    Verify dataset structure and print file information
    """
    data_path = Path(data_dir)
    patient_dirs = [d for d in data_path.iterdir() if d.is_dir()]

    print(f"\n{'='*60}")
    print(f"DATASET VERIFICATION")
    print(f"{'='*60}")
    print(f"Dataset path: {data_dir}")
    print(f"Total patient folders found: {len(patient_dirs)}")

    if len(patient_dirs) == 0:
        print("\n❌ ERROR: No patient folders found!")
        print("Please check the data_dir path.")
        return False

    print(f"\nChecking first {num_samples} patients...")

    for i, patient_dir in enumerate(patient_dirs[:num_samples]):
        print(f"\n--- Patient {i+1}: {patient_dir.name} ---")
        files = list(patient_dir.glob("*.nii.gz")) + list(patient_dir.glob("*.nii"))
        print(f"Files found: {len(files)}")
        for f in files:
            size_mb = f.stat().st_size / (1024*1024)
            print(f"  - {f.name} ({size_mb:.2f} MB)")

    print(f"\n{'='*60}")
    print("✓ Dataset verification complete!")
    print(f"{'='*60}\n")
    return True

# ==================== TRAINING ====================

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    total_dice = 0

    pbar = tqdm(dataloader, desc='Training')
    for images, masks in pbar:
        images = images.to(device)
        masks = masks.to(device)

        optimizer.zero_grad()
        outputs = model(images)

        loss = criterion(outputs, masks)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_dice += dice_score(outputs, masks)

        pbar.set_postfix({'loss': f'{loss.item():.4f}'})

    avg_loss = total_loss / len(dataloader)
    avg_dice = total_dice / len(dataloader)
    return avg_loss, avg_dice

def validate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0
    total_dice = 0

    with torch.no_grad():
        pbar = tqdm(dataloader, desc='Validation')
        for images, masks in pbar:
            images = images.to(device)
            masks = masks.to(device)

            outputs = model(images)
            loss = criterion(outputs, masks)

            total_loss += loss.item()
            total_dice += dice_score(outputs, masks)

            pbar.set_postfix({'loss': f'{loss.item():.4f}'})

    avg_loss = total_loss / len(dataloader)
    avg_dice = total_dice / len(dataloader)
    return avg_loss, avg_dice

def train_model(data_dir, num_epochs=50, batch_size=2, lr=1e-4):
    """
    Main training function
    Args:
        data_dir: Path to BraTS2020_TrainingData folder
        num_epochs: Number of training epochs
        batch_size: Batch size (keep small for 3D data)
        lr: Learning rate
    """
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # Get all patient IDs
    data_path = Path(data_dir)
    patient_ids = [d.name for d in data_path.iterdir() if d.is_dir()]

    # Split dataset
    train_ids, val_ids = train_test_split(patient_ids, test_size=0.2, random_state=42)

    print(f"Training samples: {len(train_ids)}")
    print(f"Validation samples: {len(val_ids)}")

    # Create datasets
    train_dataset = BraTSDataset(data_dir, train_ids)
    val_dataset = BraTSDataset(data_dir, val_ids)

    # Create dataloaders
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=4)

    # Create model
    model = Unetr(config).to(device)
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

    # Loss and optimizer
    criterion = BCEDiceLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)

    # Training loop
    best_dice = 0
    for epoch in range(num_epochs):
        print(f"\nEpoch {epoch+1}/{num_epochs}")

        train_loss, train_dice = train_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_dice = validate(model, val_loader, criterion, device)

        scheduler.step(val_loss)

        print(f"Train Loss: {train_loss:.4f}, Train Dice: {train_dice:.4f}")
        print(f"Val Loss: {val_loss:.4f}, Val Dice: {val_dice:.4f}")

        # Save best model
        if val_dice > best_dice:
            best_dice = val_dice
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_dice': val_dice,
            }, 'best_unetr_model.pth')
            print(f"Saved best model with Dice: {val_dice:.4f}")

    return model

# ==================== PREDICTION ====================

def predict(model_path, data_dir, patient_id, device='cuda'):
    """
    Predict segmentation for a single patient
    Args:
        model_path: Path to saved model
        data_dir: Path to BraTS2020_TrainingData folder
        patient_id: Patient folder name (e.g., 'BraTS20_Training_001')
        device: 'cuda' or 'cpu'
    """
    device = torch.device(device if torch.cuda.is_available() else 'cpu')

    # Load model
    model = Unetr(config).to(device)
    checkpoint = torch.load(model_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    # Load patient data
    dataset = BraTSDataset(data_dir, [patient_id])
    image, mask = dataset[0]

    # Predict
    with torch.no_grad():
        image = image.unsqueeze(0).to(device)
        output = model(image)
        prediction = torch.sigmoid(output) > 0.5

    # Move to CPU and convert to numpy
    prediction = prediction.cpu().numpy()[0]
    mask = mask.numpy()
    image = image.cpu().numpy()[0]

    # Calculate metrics
    dice = dice_score(torch.FloatTensor(output), torch.FloatTensor(mask).unsqueeze(0))
    print(f"Dice Score: {dice:.4f}")

    return image, prediction, mask

# ==================== VISUALIZATION ====================

def visualize_prediction(image, prediction, ground_truth, slice_idx=64, save_path='prediction.png'):
    """
    Visualize middle slice of prediction
    Args:
        image: Input image (4, H, W, D)
        prediction: Model prediction (4, H, W, D)
        ground_truth: Ground truth mask (4, H, W, D)
        slice_idx: Which slice to visualize
        save_path: Where to save the visualization
    """
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(3, 4, figsize=(16, 12))

    # Show each modality
    modalities = ['FLAIR', 'T1', 'T1ce', 'T2']
    for i, modality in enumerate(modalities):
        axes[0, i].imshow(image[i, :, :, slice_idx], cmap='gray')
        axes[0, i].set_title(f'{modality}')
        axes[0, i].axis('off')

    # Show ground truth
    classes = ['Background', 'NCR/NET', 'ED', 'ET']
    for i, class_name in enumerate(classes):
        axes[1, i].imshow(ground_truth[i, :, :, slice_idx], cmap='jet')
        axes[1, i].set_title(f'GT: {class_name}')
        axes[1, i].axis('off')

    # Show predictions
    for i, class_name in enumerate(classes):
        axes[2, i].imshow(prediction[i, :, :, slice_idx], cmap='jet')
        axes[2, i].set_title(f'Pred: {class_name}')
        axes[2, i].axis('off')

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"Visualization saved to {save_path}")
    plt.close()

# ==================== MAIN ====================

if __name__ == "__main__":
    # ========== STEP 0: VERIFY DATASET ==========
    print("="*60)
    print("STEP 0: VERIFYING DATASET")
    print("="*60)

    data_dir = "/kaggle/input/brats20-dataset-training-validation/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData"

    # Verify dataset exists and is accessible
    if not verify_dataset(data_dir, num_samples=3):
        print("\n❌ Dataset verification failed. Please check the path.")
        print("\nTip: Update the data_dir variable to match your Kaggle dataset path.")
        exit(1)

    # ========== STEP 1: TRAINING ==========
    print("="*60)
    print("STEP 1: TRAINING THE MODEL")
    print("="*60)

    data_dir = "/kaggle/input/brats20-dataset-training-validation/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData"

    # Train the model
    print("\nStarting training...")
    model = train_model(
        data_dir=data_dir,
        num_epochs=1,  # Start with 10 epochs for testing, increase to 50+ for better results
        batch_size=1,   # Use batch_size=1 if you have memory issues, increase to 2 if possible
        lr=1e-4
    )

    print("\n✓ Training completed!")
    print("Best model saved as 'best_unetr_model.pth'")

    # ========== STEP 2: PREDICTIONS ==========
    print("\n" + "="*60)
    print("STEP 2: MAKING PREDICTIONS")
    print("="*60)

    # Get some patient IDs for prediction
    data_path = Path(data_dir)
    all_patients = [d.name for d in data_path.iterdir() if d.is_dir()]
    test_patients = all_patients[:5]  # Test on first 5 patients

    print(f"\nTesting on {len(test_patients)} patients...")

    for i, patient_id in enumerate(test_patients):
        print(f"\n--- Patient {i+1}/{len(test_patients)}: {patient_id} ---")

        try:
            # Make prediction
            image, prediction, ground_truth = predict(
                model_path='best_unetr_model.pth',
                data_dir=data_dir,
                patient_id=patient_id,
                device='cuda'
            )

            # Visualize results
            visualize_prediction(
                image,
                prediction,
                ground_truth,
                slice_idx=64,
                save_path=f'prediction_{patient_id}.png'
            )

            # Print statistics
            print(f"\nPrediction Statistics:")
            print(f"  Background voxels: {prediction[0].sum():.0f}")
            print(f"  NCR/NET voxels: {prediction[1].sum():.0f}")
            print(f"  ED voxels: {prediction[2].sum():.0f}")
            print(f"  ET voxels: {prediction[3].sum():.0f}")

        except Exception as e:
            print(f"Error processing {patient_id}: {str(e)}")
            continue

    print("\n" + "="*60)
    print("ALL DONE!")
    print("="*60)
    print("\nSummary:")
    print("- Model trained and saved to 'best_unetr_model.pth'")
    print("- Predictions visualized and saved as 'prediction_*.png'")
    print("\nYou can now use the model for inference on new patients!")

    # ========== BONUS: Single Patient Prediction Example ==========
    print("\n" + "="*60)
    print("BONUS: How to predict on a single new patient:")
    print("="*60)
    print("""
# Example code:
image, pred, gt = predict(
    model_path='best_unetr_model.pth',
    data_dir='/path/to/data',
    patient_id='BraTS20_Training_001',
    device='cuda'
)

visualize_prediction(image, pred, gt, save_path='my_prediction.png')
    """)

image, pred, gt = predict(
    model_path="/kaggle/working/best_unetr_model.pth",
    data_dir='/kaggle/input/brats20-dataset-training-validation/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData',
    patient_id='BraTS20_Training_001',
    device='cuda'
)

visualize_prediction(image, pred, gt, save_path='my_prediction.png')

def predict(model_path, data_dir, patient_id, device='cuda'):
    """
    Predict segmentation for a single patient
    Args:
        model_path: Path to saved model
        data_dir: Path to BraTS2020_TrainingData folder
        patient_id: Patient folder name (e.g., 'BraTS20_Training_001')
        device: 'cuda' or 'cpu'
    """
    device = torch.device(device if torch.cuda.is_available() else 'cpu')

    # Load model
    model = Unetr(config).to(device)
    checkpoint = torch.load(model_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    # Load patient data
    dataset = BraTSDataset(data_dir, [patient_id])
    image, mask = dataset[0]

    # Predict
    with torch.no_grad():
        image_input = image.unsqueeze(0).to(device)
        output = model(image_input)
        prediction = torch.sigmoid(output) > 0.5

    # Calculate metrics (move tensors to same device)
    output_cpu = output.cpu()
    mask_tensor = mask.unsqueeze(0)
    dice = dice_score(output_cpu, mask_tensor)
    print(f"Dice Score: {dice:.4f}")

    # Move to CPU and convert to numpy
    prediction = prediction.cpu().numpy()[0]
    mask = mask.numpy()
    image = image.numpy()

    return image, prediction, mask

def visualize_prediction(image, prediction, ground_truth, slice_idx=64, save_path='prediction.png'):
    """
    Visualize middle slice of prediction
    Args:
        image: Input image (4, H, W, D)
        prediction: Model prediction (4, H, W, D)
        ground_truth: Ground truth mask (4, H, W, D)
        slice_idx: Which slice to visualize
        save_path: Where to save the visualization
    """
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(3, 4, figsize=(16, 12))

    # Show each modality
    modalities = ['FLAIR', 'T1', 'T1ce', 'T2']
    for i, modality in enumerate(modalities):
        axes[0, i].imshow(image[i, :, :, slice_idx], cmap='gray')
        axes[0, i].set_title(f'{modality}')
        axes[0, i].axis('off')

    # Show ground truth
    classes = ['Background', 'NCR/NET', 'ED', 'ET']
    for i, class_name in enumerate(classes):
        axes[1, i].imshow(ground_truth[i, :, :, slice_idx], cmap='jet')
        axes[1, i].set_title(f'GT: {class_name}')
        axes[1, i].axis('off')

    # Show predictions
    for i, class_name in enumerate(classes):
        axes[2, i].imshow(prediction[i, :, :, slice_idx], cmap='jet')
        axes[2, i].set_title(f'Pred: {class_name}')
        axes[2, i].axis('off')

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"Visualization saved to {save_path}")
    plt.close()

image, pred, gt = predict(
    model_path="/kaggle/working/best_unetr_model.pth",
    data_dir='/kaggle/input/brats20-dataset-training-validation/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData',
    patient_id='BraTS20_Training_001',
    device='cuda'
)

visualize_prediction(image, pred, gt, save_path='my_prediction.png')

visualize_3d_comparison(image, pred, gt)

def visualize_prediction(image, prediction, ground_truth, slice_idx=64, save_path='prediction.png'):
    """
    Visualize middle slice of prediction
    Args:
        image: Input image (4, H, W, D)
        prediction: Model prediction (4, H, W, D)
        ground_truth: Ground truth mask (4, H, W, D)
        slice_idx: Which slice to visualize
        save_path: Where to save the visualization
    """
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(3, 4, figsize=(16, 12))

    # Show each modality
    modalities = ['FLAIR', 'T1', 'T1ce', 'T2']
    for i, modality in enumerate(modalities):
        axes[0, i].imshow(image[i, :, :, slice_idx], cmap='gray')
        axes[0, i].set_title(f'{modality}')
        axes[0, i].axis('off')

    # Show ground truth
    classes = ['Background', 'NCR/NET', 'ED', 'ET']
    for i, class_name in enumerate(classes):
        axes[1, i].imshow(ground_truth[i, :, :, slice_idx], cmap='jet')
        axes[1, i].set_title(f'GT: {class_name}')
        axes[1, i].axis('off')

    # Show predictions
    for i, class_name in enumerate(classes):
        axes[2, i].imshow(prediction[i, :, :, slice_idx], cmap='jet')
        axes[2, i].set_title(f'Pred: {class_name}')
        axes[2, i].axis('off')

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"Visualization saved to {save_path}")
    plt.close()

# After training, visualize any patient
image, pred, gt = predict(
    model_path='best_unetr_model.pth',
    data_dir='/kaggle/input/brats20-dataset-training-validation/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData',
    patient_id='BraTS20_Training_001',
    device='cuda'
)

# View single slice
visualize_prediction(image, pred, gt)

# View multiple slices
visualize_3d_comparison(image, pred, gt)

def visualize_3d_comparison(image, prediction, ground_truth, save_path='comparison_3d.png'):
    """
    Show multiple slices in a grid for better 3D understanding
    Args:
        image: Input image (4, H, W, D)
        prediction: Model prediction (4, H, W, D)
        ground_truth: Ground truth mask (4, H, W, D)
        save_path: Where to save the visualization
    """
    import matplotlib.pyplot as plt

    depth = image.shape[-1]
    # Select 6 evenly spaced slices
    slice_indices = [depth//7, 2*depth//7, 3*depth//7, 4*depth//7, 5*depth//7, 6*depth//7]

    fig, axes = plt.subplots(6, 3, figsize=(15, 25))

    for row, slice_idx in enumerate(slice_indices):
        # Show FLAIR modality
        axes[row, 0].imshow(image[0, :, :, slice_idx], cmap='gray')
        axes[row, 0].set_title(f'FLAIR - Slice {slice_idx}', fontsize=12)
        axes[row, 0].axis('off')

        # Show combined ground truth (all tumor regions)
        gt_combined = (ground_truth[1:, :, :, slice_idx].sum(axis=0) > 0).astype(float)
        axes[row, 1].imshow(image[0, :, :, slice_idx], cmap='gray')
        axes[row, 1].imshow(gt_combined, cmap='Reds', alpha=0.5)
        axes[row, 1].set_title(f'Ground Truth - Slice {slice_idx}', fontsize=12)
        axes[row, 1].axis('off')

        # Show combined prediction
        pred_combined = (prediction[1:, :, :, slice_idx].sum(axis=0) > 0).astype(float)
        axes[row, 2].imshow(image[0, :, :, slice_idx], cmap='gray')
        axes[row, 2].imshow(pred_combined, cmap='Greens', alpha=0.5)
        axes[row, 2].set_title(f'Prediction - Slice {slice_idx}', fontsize=12)
        axes[row, 2].axis('off')

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"✓ 3D comparison saved to {save_path}")
    plt.show()
    plt.close()

